version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: script/stop-container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: script/start-container.sh
      timeout: 300 
      runas: root
